/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CATEGORIAS;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tazita y mayeyita pw
 */
public class ConsultarCategoria extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarCategoria
     */
    public ConsultarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCategoriaID = new javax.swing.JTextField();
        btnConsultarCategoria = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Categoria");

        txtCategoriaID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtCategoriaID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnConsultarCategoria.setBackground(new java.awt.Color(0, 153, 0));
        btnConsultarCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnConsultarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarCategoria.setText("Consultar");
        btnConsultarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(txtCategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnConsultarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(125, 125, 125)
                .addComponent(txtCategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnConsultarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCategoriaActionPerformed

        try {
        // Captura el ID ingresado por el usuario
        Long categoriaId = Long.parseLong(txtCategoriaID.getText());

        // Crea una instancia del DAO y realiza la consulta
        categoriaDAO dao = new categoriaDAO();
        categoriaDTO categoria = dao.readCategoriaById(categoriaId);

        // Muestra el resultado al usuario
        if (categoria != null) {
            JOptionPane.showMessageDialog(this,
                "Categoría encontrada:\n\nID: " + categoria.getCategoriaId() + "\nNombre: " + categoria.getNombre(),
                "Resultado de la Consulta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "No se encontró una categoría con el ID proporcionado.",
                "Resultado de la Consulta", JOptionPane.WARNING_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Por favor, ingrese un ID válido.",
            "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error al realizar la consulta: " + e.getMessage(),
            "Error en la Base de Datos", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnConsultarCategoriaActionPerformed

    
    public static void main(String[] args) {
        // Inicia la ventana de la interfaz gráfica
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCategoria().setVisible(true); // Muestra la ventana
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCategoriaID;
    // End of variables declaration//GEN-END:variables
}
