CREATE OR REPLACE TRIGGER TRG_CREAR_CATEGORIA
AFTER INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA (ACCION, TABLA_AFECTADA, FECHA_ACCION, USUARIO)
    VALUES ('INSERT', 'CATEGORIAS', SYSDATE, USER);  -- 'USER' devuelve el usuario conectado en la sesión
END;
/
