CREATE OR REPLACE PROCEDURE SP_OBTENER_NOTICIAS_POR_FECHA(
    P_FECHA IN DATE,
    P_RESULTADO OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT TITULO, CONTENIDO, ESCRITOR, FECHA_PUBLICADA 
        FROM NOTICIA
        WHERE FECHA_PUBLICADA = P_FECHA;
END SP_OBTENER_NOTICIAS_POR_FECHA;
